// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QPQFclFQ5BVp_Z3x7BbF_lDAIU0uFpM',
    appId: '1:833794511605:web:2d6b67e52c9b82483eabbc',
    messagingSenderId: '833794511605',
    projectId: 'fitpulse743',
    authDomain: 'fitpulse743.firebaseapp.com',
    storageBucket: 'fitpulse743.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAuC5B-TNgXhgvPS0WG6r2hyNrlkGFMI',
    appId: '1:833794511605:android:15d273d42669edca3eabbc',
    messagingSenderId: '833794511605',
    projectId: 'fitpulse743',
    storageBucket: 'fitpulse743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIvrekoUYc0UjkUItDjrhal2mhbzi5Jk',
    appId: '1:833794511605:ios:a5e1aa5548f0da0d3eabbc',
    messagingSenderId: '833794511605',
    projectId: 'fitpulse743',
    storageBucket: 'fitpulse743.firebasestorage.app',
    iosBundleId: 'com.acrocoder.fitpulse.app',
  );
}
